FROM --platform=linux/amd64 python:3.12.8-slim

WORKDIR /app

COPY requirements_ui.txt .

RUN pip install --no-cache-dir -r requirements_ui.txt

COPY /frontend /app/frontend

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]